
from .system_prompts import (
    SOFIA_PERSONALITY,
    RECEPTION_AGENT_SYSTEM,
    SUPPORT_AGENT_SYSTEM,
    LEADSALES_AGENT_SYSTEM
)

from .extraction_prompts import (
    EXTRACT_INTENT_AND_ENTITIES,
    EXTRACT_NAME_ONLY,
    EXTRACT_PROPERTY_FEATURES
)

from .classification_prompts import (
    CLASSIFY_INTENTION,
    CLASSIFY_SUPPORT_CATEGORY,
    CLASSIFY_TRIPATH_INTENT
)

__all__ = [
    # System prompts
    "SOFIA_PERSONALITY",
    "RECEPTION_AGENT_SYSTEM",
    "SUPPORT_AGENT_SYSTEM",
    "LEADSALES_AGENT_SYSTEM",

    # Extraction prompts
    "EXTRACT_INTENT_AND_ENTITIES",
    "EXTRACT_NAME_ONLY",
    "EXTRACT_PROPERTY_FEATURES",

    # Classification prompts
    "CLASSIFY_INTENTION",
    "CLASSIFY_SUPPORT_CATEGORY",
    "CLASSIFY_TRIPATH_INTENT"
]
