# Prompts centralizados para el sistema

from .system_prompts import (
    SOFIA_PERSONALITY,
    RECEPTION_AGENT_SYSTEM,
    SUPPORT_AGENT_SYSTEM,
    LEADSALES_AGENT_SYSTEM
)

from .extraction_prompts import (
    EXTRACT_INTENT_AND_ENTITIES,
    EXTRACT_NAME_ONLY,
    EXTRACT_PROPERTY_FEATURES
)

from .classification_prompts import (
    CLASSIFY_INTENTION,
    CLASSIFY_SUPPORT_CATEGORY,
    CLASSIFY_TRIPATH_INTENT
)

from .llm_service_prompts import (
    CLASSIFY_QUESTION_VS_NEED_SYSTEM,
    CLASSIFY_QUESTION_VS_NEED_USER
)

from .generator_prompts import (
    GENERATE_CONTEXTUAL_RESPONSE_SYSTEM,
    GENERATE_CONTEXTUAL_RESPONSE_USER,
    GENERATE_FOLLOWUP_SYSTEM,
    GENERATE_FOLLOWUP_USER
)

from .classifier_prompts import (
    CLASSIFY_INTENTION_SYSTEM,
    CLASSIFY_INTENTION_USER,
    ANALYZE_SENTIMENT_SYSTEM,
    ANALYZE_SENTIMENT_USER
)

__all__ = [
    # System prompts
    "SOFIA_PERSONALITY",
    "RECEPTION_AGENT_SYSTEM",
    "SUPPORT_AGENT_SYSTEM",
    "LEADSALES_AGENT_SYSTEM",

    # Extraction prompts
    "EXTRACT_INTENT_AND_ENTITIES",
    "EXTRACT_NAME_ONLY",
    "EXTRACT_PROPERTY_FEATURES",

    # Classification prompts (legacy)
    "CLASSIFY_INTENTION",
    "CLASSIFY_SUPPORT_CATEGORY",
    "CLASSIFY_TRIPATH_INTENT",

    # LLM Service prompts
    "CLASSIFY_QUESTION_VS_NEED_SYSTEM",
    "CLASSIFY_QUESTION_VS_NEED_USER",

    # Generator prompts
    "GENERATE_CONTEXTUAL_RESPONSE_SYSTEM",
    "GENERATE_CONTEXTUAL_RESPONSE_USER",
    "GENERATE_FOLLOWUP_SYSTEM",
    "GENERATE_FOLLOWUP_USER",

    # Classifier prompts (new structure)
    "CLASSIFY_INTENTION_SYSTEM",
    "CLASSIFY_INTENTION_USER",
    "ANALYZE_SENTIMENT_SYSTEM",
    "ANALYZE_SENTIMENT_USER"
]
